pipelines:
  default:
      - step:
          name: Deploy to test
          deployment: test
          script:
            - echo "Deploy is Ok!"
  #            - pipe: atlassian/sftp-deploy:0.5.3
  #              variables:
  #                USER: $USER_REMOTE
  #                SERVER: $SERVER_IP
  #                REMOTE_PATH: $PATH_REMOTE
  #                LOCAL_PATH: './' # Optional.
  #                # SSH_KEY: '<string>' # Optional.
  #                # PASSWORD: '<string>' # Optional.
  #                # EXTRA_ARGS: '<string>' # Optional.
  #                # DEBUG: '<boolean>' # Optional.

  custom: # Pipelines that can only be triggered manually
    deployment-to-test:
      - step:
          name: Deploy to test
          deployment: test
          script:
            - pipe: atlassian/sftp-deploy:0.5.3
              variables:
                USER: $USER_REMOTE
                SERVER: $SERVER_IP
                REMOTE_PATH: $PATH_REMOTE
                LOCAL_PATH: './' # Optional.
                # SSH_KEY: '<string>' # Optional.
                # PASSWORD: '<string>' # Optional.
                # EXTRA_ARGS: '<string>' # Optional.
                # DEBUG: '<boolean>' # Optional.
    run-tests:
      - step:
          script:
            - echo "Start Test"
            - pipe: atlassian/ssh-run:0.2.3
              variables:
                SSH_USER: $USER_REMOTE
                SERVER: $SERVER_IP
                MODE: 'command'
                COMMAND: 'cd /home/andrii/www/paradam-test.acer && ./remote-script.sh'

    deployment-to-prod:
      - step:
          script:
            - echo "Manual triggers for deployments are awesome!"
  branches:  # Конвейеры, которые запускаются автоматически при фиксации ветви, также могут запускаться вручную
    staging:
      - step:
          script:
            - echo "Automated pipelines are cool too."