version: '2'
services:
  php:
    image: yii2-php-supervisor:latest
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    command: bash -c "a2enmod ssl && a2ensite new-default-ssl && service apache2 reload && supervisord -c /etc/supervisor/supervisord.conf && supervisorctl -c /etc/supervisor/supervisord.conf"
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
      - "9505:9505"
      - "9503:9503"
    networks:
      - default
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3336:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paradam
      MYSQL_USER: splaa
      MYSQL_PASSWORD: splaa1977
    volumes:
      - "./database:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080"